#Common Configuration Parameters
gem2_robot: "nao"
gem2_left_foot_wrench_topic: "/gem2/LLeg/force_torque_states"  #left foot FT
gem2_right_foot_wrench_topic: "/gem2/RLeg/force_torque_states" #right foot FT
gem2_freq: 100    #min freq of all topics
gem2_lfoot_frame: "l_ankle"   #left foot frame 
gem2_rfoot_frame: "r_ankle"   #right foot frame 
#Unsupervisead Gait Phase Learning Parameters
useUL: False  #Use Unsupervised Learning (Dimensionality Reduction + Clustering) for  Gait Phase Estimation
#Only if use_UL is True
gem2_imu_topic: "/gem2/rel_base_imu" # base_link (body) IMU
gem2_com_topic: "/gem2/rel_CoM/pose"  #relative to base_link (body) CoM - computed with kinematics
gem2_plot_results: True #plot the results only works when Dimensionality Reduction is performed
gem2_dim: 2
gem2_gt_comparison: False  #compare to ground-truth, to do so user must supply true friction coefficient mu and ground reaction forces and torques.
gem2_save: True  #Save the Training Results to load in real-time
#gem2_dim_reduction: "supervisedClassifier" 
#gem2_dim_reduction: "supervisedVariationalAutoencoders" 
#gem2_dim_reduction: "pca"
gem2_dim_reduction: "supervisedAutoencoders"
#gem2_dim_reduction: "autoencoders" 

useLabels: True
gem2_validation: True
gem2: True
gem2_clustering: "gmm" #gmm or kmeans supported at the current time
gem2_train_path: "../GEM2_nao_training" #path to training data relative to src e.g. "../gem2/src/gem2_train_path", data must have same(or approx. same) sampling rate e.g. gem2_freq.
gem2_validation_path: "../GEM2_nao_validation/NAO2" #path to training data relative to src e.g. "../gem2/src/gem2_train_path", data must have same(or approx. same) sampling rate e.g. gem2_freq.

